config/routes.rb
Rails.application.routes.draw do
  root to: 'repositories#index'

  resources :repositories, only: %i[index]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    @query = params[:query]

    resolve("repositories.search").(@query) do |m|
      m.success do |result|
        @repos = result
      end

      m.failure do |error|
        @error = error
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitReader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Git Reader</a>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/repositories/_repo.html.erb
<div>
  <div>
    <a href="<%= repo[:url] %>" target="_blank">
      <%= repo[:name] %>
    </a>
    <img src="<%= repo[:avatar_url] %>">
  </div>
  <div>Owner: <%= repo[:owner] %></div>
  <div>Description: <%= repo[:description] %></div>
  <div>Stars: <%= repo[:stars] %></div>
  <div>Watchers: <%= repo[:watchers] %></div>
  <div>Language: <%= repo[:language] %></div>
  <div>Tags: <%= repo[:tags] %></div>
  <div>Forks: <%= repo[:forks] %></div>
  <div>Open Issues: <%= repo[:issues] %></div>
</div>

app/views/repositories/index.html.erb
<div>
  <%= form_tag(repositories_path, method: "get") do %>
    <%= label_tag(:query, "Search Github Repositories") %>
    <%= text_field_tag(:query, @query) %>
    <%= submit_tag("Go!") %>
  <% end %>
</div>


<% if @repos.present? %>
  <% @repos.each do |repo| %>
    <%= render partial: "repo", locals: { repo: repo } %>
    <hr />
  <% end %>
<% elsif @error.present? %>
  <h1><%= @error %></h1>
<% else %>
  <h1>Here be dragons</h1>
<% end %>